title: Oliver Davies
subtitle: Drupal, Symfony, PHP, Linux
description: Oliver Davies, Drupal Developer
email: oliver+website@oliverdavies.uk

author:
    name: Oliver Davies
    bio: Oliver Davies is a Drupal Developer and System Administrator based in the UK. He is a Lead Developer at <a href="http://ctidigital.com">CTI Digital</a> and also provides freelance consultancy services for Drupal websites, PHP applications and Linux servers.

twitter:
    url: http://twitter.com/opdavies
    name: opdavies
linkedin:
    url: http://uk.linkedin.com/in/opdavies
drupalorg:
    url: https://www.drupal.org/user/381388
    url_nice: https://www.drupal.org/u/opdavies
    name: opdavies
    uid: 381388
github:
    url: http://github.com/opdavies
    name: opdavies
irc:
    name: opdavies
lanyrd:
    url: http://lanyrd.com/profile/opdavies
joindin:
    url: https://joind.in/user/view/27119
ansible_galaxy:
    url: https://galaxy.ansible.com/list#/users/14560
gravatar:
    url: //www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png
flickr:
    url: https://www.flickr.com/photos/133286555@N04
speakerdeck:
    url: https://speakerdeck.com/opdavies

apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

main_menu:
    experience: { title: Experience, href: /experience/ }
    testimonials: { title: Testimonials, href: /testimonials/ }
    talks: { title: Talks, href: /talks/ }
    blog: { title: Blog, href: /blog/ }
    contact: { title: Contact, href: /contact/ }

meetups:
    drupalbristol: { name: Drupal Bristol, logo: drupal-bristol.jpeg, url: https://groups.drupal.org/bristol-west-uk }
    phpsw: { name: PHPSW, logo: phpsw.jpeg, url: http://phpsw.uk }
    swdug: { name: SWDUG, logo: swdug.png, url: http://swdug.org.uk }
    swlug: { name: SWLUG, logo: swlug.png, url: http://swlug.org.uk }
    accbristol: { name: Accessible Bristol, logo: accessible-bristol.png, url: http://www.accessiblebristol.org.uk }
    # udiff: { name: Unified Diff, logo: unified-diff.png, url: http://unifieddiff.co.uk }
    nwdug: { name: NWDUG, logo: nwdug.jpg, url: http://www.meetup.com/nwdrupal }

hightlightjs_style: default
digitalocean_referral: a913b4b00d4a
default_date_format: jS F, Y
fuzzy_date_format: F Y
title_separator: "|"
html_lang: en-GB

availability:
    status:
        day: { available: no, start: ~, end: ~ }
        evenings: { available: limited, start: 2015-08-10, end: ~ }
    text:
        day:
            yes: <i class="fa fa-thumbs-o-up text-success"></i> Available for day contract work
            no: <i class="fa fa-thumbs-o-down text-danger"></i> Not available for day contract work
        evenings:
            yes: <i class="fa fa-thumbs-o-up text-success"></i> Available for weekend/evening freelance work
            limited: <i class="fa fa-thumbs-o-up text-warning"></i> Limited availability for weekend/evening freelance work
            no: <i class="fa fa-thumbs-o-down text-danger"></i> Not availabile for weekend/evening freelance work

companies:
    horse_country:
        title: 'Horse & Country TV'
    zooba:
        title: Zooba Ltd
    proctors:
        title: 'Proctor & Stevenson'
        website: http://www.proctors.co.uk
    nomensa:
        title: Nomensa
        website: http://www.nomensa.com
    precedent:
        title: Precedent
        website: http://precedent.com
    trent:
        title: Trent Design
        website: http://www.trentdesign.net
    lab_class:
        title: Lab Class
        website: http://labclass.co.uk
    drupal_association:
        title: Drupal Association
        website: https://assoc.drupal.org
    microserve:
        title: Microserve
        website: https://microserve.io
