sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:slug_title/
        taxonomies:
            - tags

    projects:
        permalink: projects/:slug_title/
        taxonomies:
            - skills
            - tags

    talks:
        permalink: talks/:year/:month/:day/:filename/
        taxonomies:
            - tags
